# Generated by Django 3.1.7 on 2021-03-08 20:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ein', models.CharField(max_length=9, null=True)),
                ('name', models.CharField(max_length=255)),
                ('address_line_1', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(db_index=True, max_length=2)),
                ('zipcode', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Award',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.TextField()),
                ('amount_dollars', models.PositiveIntegerField()),
                ('filing_url', models.URLField()),
                ('filer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards_given', to='filings.organization')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='awards_received', to='filings.organization')),
            ],
        ),
    ]
